root: true
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']
ignorePatterns: ['generated/']
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
